apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nsfwcheck.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nsfwcheck.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nsfwcheck.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nsfwcheck.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: URLSAFE_SERVICE_URL
              {{- if .Values.serviceDiscovery.useFullDomain }}
              value: "http://urlsafe.{{ .Values.namespace }}.svc.{{ .Values.serviceDiscovery.clusterDomain }}:8000"
              {{- else }}
              value: "http://urlsafe:8000"
              {{- end }}
            - name: IMAGESAFE_SERVICE_URL
              {{- if .Values.serviceDiscovery.useFullDomain }}
              value: "http://imagesafe.{{ .Values.namespace }}.svc.{{ .Values.serviceDiscovery.clusterDomain }}:3000"
              {{- else }}
              value: "http://imagesafe:3000"
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
