apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsfwcheck.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nsfwcheck.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nsfwcheck.service.port }}
      targetPort: {{ .Values.nsfwcheck.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nsfwcheck.selectorLabels" . | nindent 4 }}
