apiVersion: v1
kind: Service
metadata:
  name: urlsafe
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: urlsafe
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.urlsafe.service.port }}
      targetPort: {{ .Values.urlsafe.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: urlsafe
